import = [
  #"~/.config/alacritty/themes/catppuccin-latte.toml"
  #"~/.config/alacritty/themes/catppuccin-frappe.toml"
  #"~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 17.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/fish"

[window]
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
